spring:
  application:
    name: 01blog
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/blog
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update